apiVersion: v1
kind: Service
metadata:
  name: school-committee
  namespace: statex-apps
  labels:
    app: school-committee
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: school-committee
  ports:
    - protocol: TCP
      port: 4800
      targetPort: 4800
      name: http
